baseurl: https://dearbojack.github.io/decode
languageCode: en-us
title: "null"
theme: hugo-ivy
googleAnalytics: ""
disqusShortname: ""
preserveTaxonomyNames: true
publishDir: "docs"
footnotereturnlinkcontents: â†©
enableGitInfo: true

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/
  journal: /journal/:year/:month/:day/:slug/

menu:
  main:
    - name: "home"
      url: "/"
      weight: 1
    - name: "about"
      url: "/about/"
      weight: 2
    # let's remove all this and keep it simple
    # - name: "Tags"
    #   url: "/tags/"
    #   weight: 3
    - name: "rss"
      url: "/index.xml"

params:
  description: "system log"
  footer: "&copy; d&d 2022 | [github](https://github.com/dearbojack)"
  highlightjsLang: ["javascript"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
    style: monokai
    tabWidth: 2
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
  goldmark:
    extensions:
      footnote: true
      taskList: true
      table: true
    renderer:
      unsafe: true
